name: iOS CI/CD - AIChatBuddy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-upload:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: Decode GoogleService-Info.plist
      run: echo "${{ secrets.GOOGLE_PLIST_BASE64 }}" | base64 --decode > AIChatBuddy/Resources/GoogleService-Info.plist
           echo "${{ secrets.SECRETS_PLIST_BASE64 }}" | base64 --decode > AIChatBuddy/Resources/Secrets.plist

    - name: Install dependencies (SPM)
      run: xcodebuild -resolvePackageDependencies -project AIChatBuddy.xcodeproj

    - name: Run tests
      run: |
        xcodebuild test \
          -project AIChatBuddy.xcodeproj \
          -scheme AIChatBuddy \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'

    - name: Build and archive
      run: |
        xcodebuild clean archive \
          -project AIChatBuddy.xcodeproj \
          -scheme AIChatBuddy \
          -archivePath ${{ github.workspace }}/build/AIChatBuddy.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -allowProvisioningUpdates \
          -destination 'generic/platform=iOS'

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ${{ github.workspace }}/build/AIChatBuddy.xcarchive \
          -exportPath ${{ github.workspace }}/build/export \
          -exportOptionsPlist exportOptions.plist

    - name: Upload to TestFlight
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file "${{ github.workspace }}/build/export/AIChatBuddy.ipa" \
          --username "${{ secrets.APPLE_ID }}" \
          --password "${{ secrets.APP_SPECIFIC_PASSWORD }}"
